version: "3"
services:
    db:
        build: ./db/
        image: zhequant-db
        #command: --auth # currently do not use authentication
        volumes:
            - ./data/mongodb/data/db/:/data/db/
            - ./data/mongodb/data/configdb/:/data/mongodb/data/configdb/
        networks:
            - mynetwork
    rabbitmq:
        image: rabbitmq:3.6.6
        hostname: myhostname
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq
        networks:
            - mynetwork
    webserver:
        build: ./webserver
        image: zhequant-webserver-backend
        ports:
            - "3000:3000"
        networks:
            - mynetwork
    pbrain:
        build: ./pbrain
        image: zhequant-brain-python
        networks:
            - mynetwork
    admin:
        build: ./admin
        image: zhequant-admin-console
        networks:
            - mynetwork

networks:
    mynetwork:
